projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://bcgraph.herokuapp.com/bcgraph
  database:
    schemaPath: src/generated/prisma.graphql
      includes: [
        "prisma.graphql",
        "datamodel.graphql",
      ]
      extensions:
        prisma: database/prisma.yml
        codegen:
          - generator: prisma-binding
            language: typescript
            output:
              binding: src/generated/prisma.ts