version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:0d:5c:b0:da:c9:c4:92:ed:49:8d:14:e7:5f:02:f9"
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "sh deploy-api.sh"
      - run: echo 'deployment for api.bcweb.me successful'
      #- run: docker build -t bcgraph:latest .
      # - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      # - run: docker tag bcgraph:latest bcapp/bcweb:latest
      # - run: docker push bcapp/bcgraph:latest
      # - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "echo 'bccicd SSH Succeeded'"
  deploy_api:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "c3:0d:5c:b0:da:c9:c4:92:ed:49:8d:14:e7:5f:02:f9"
      - run: echo 'Starting Deployment For bcgraph'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_api:
          requires:
            - build





              
