# zeit/serve 


# traefik
  reverse-proxy:
    image: traefik 
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"    # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  whoami:
    image: containous/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
      
# prisma dev
  prisma:
    container_name: bcprisma
    image: prismagraphql/prisma:1.14
    restart: always
    ports: 
      - "8008:8008"
    environment:
      name: bcprisma
      stage: test
      PRISMA_CONFIG: |
        endpoint: http://begincoffeesprisma.herokuapp.com/bcprisma/test
        secret: 576eef8cb1f325292da28c44ff8c48237782409c
        datamodel: database/datamodel.graphql
        databases:
          default:
            connector: postgres
            migrations: true
            connectionLimit: 2
            uri: ${DATABASE_URL}?ssl=1 